# Simple static site configuration for DHA Document Generator
# No build process needed - just serve the HTML file

[build]
  # No build command needed for static HTML
  command = "echo 'No build needed'"
  
  # Serve files from root directory
  publish = "."

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"