# Netlify Configuration for DHA Digital Services Platform
# Department of Home Affairs Digital Platform - Production Ready

[build]
  # Build command for full-stack Node.js + React application
  command = "npm ci && cd client && npm ci && cd .. && npm run build"
  
  # Client build output directory (Vite builds to client/dist)
  publish = "client/dist"
  
  # Server functions directory for Netlify Functions (optional fallback)
  functions = "netlify/functions"

[build.environment]
  # Node.js version requirement
  NODE_VERSION = "20"
  
  # Build environment
  NODE_ENV = "production"
  
  # Enable npm ci for faster, deterministic builds
  NPM_FLAGS = "--prefer-offline --no-audit"

# Server-side API routing for full-stack deployment
[[redirects]]
  # Health check endpoint (must come before general API routes)
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  # API routes - Proxy to serverless functions
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  # SPA fallback - All other routes serve index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for government platform
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # HTTPS enforcement
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy for government compliance
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.openai.com"

# Static asset optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Cache JavaScript files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Functions configuration
[functions]
  # External Node.js modules for serverless functions
  external_node_modules = [
    "@ai-sdk/openai", 
    "@anthropic-ai/sdk", 
    "express", 
    "pg", 
    "puppeteer",
    "serverless-http",
    "cors",
    "helmet", 
    "compression",
    "express-rate-limit",
    "bcryptjs",
    "jsonwebtoken"
  ]
  
  # Node.js runtime bundler
  node_bundler = "nft"
  
  # Function timeout (max 26 seconds for Netlify)
  timeout = 26

# Forms handling (for contact forms, applications, etc.)
[forms]
  # Basic form handling - useful for government applications
  spam-filtering = true

# Environment variables (set these in Netlify dashboard)
# Required environment variables:
# - DATABASE_URL: PostgreSQL connection string
# - SESSION_SECRET: Session encryption key
# - OPENAI_API_KEY: AI services (if used)
# - ANTHROPIC_API_KEY: AI services (if used)

# Development preview settings
[context.branch-deploy]
  command = "npm ci && cd client && npm ci && cd .. && npm run build"

[context.deploy-preview]
  command = "npm ci && cd client && npm ci && cd .. && npm run build"

# Production deployment settings
[context.production]
  command = "npm ci && cd client && npm ci && cd .. && npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"
    
# Build plugins for optimization
# Express + Vite optimized configuration
# No Next.js plugins needed for this stack

# Performance optimizations
[dev]
  # Local development server (for netlify dev command)
  command = "npm run dev"
  port = 5173
  publish = "client/dist"