[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NODE_ENV = "production"
  # Build environment variables for proper compilation
  JWT_SECRET = "${JWT_SECRET}"
  SESSION_SECRET = "${SESSION_SECRET}"
  ENCRYPTION_KEY = "${ENCRYPTION_KEY}"
  VITE_ENCRYPTION_KEY = "${VITE_ENCRYPTION_KEY}"
  MASTER_ENCRYPTION_KEY = "${MASTER_ENCRYPTION_KEY}"
  QUANTUM_ENCRYPTION_KEY = "${QUANTUM_ENCRYPTION_KEY}"
  BIOMETRIC_ENCRYPTION_KEY = "${BIOMETRIC_ENCRYPTION_KEY}"
  DOCUMENT_SIGNING_KEY = "${DOCUMENT_SIGNING_KEY}"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"
  ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"
  DHA_NPR_API_KEY = "${DHA_NPR_API_KEY}"
  DHA_ABIS_API_KEY = "${DHA_ABIS_API_KEY}"
  ICAO_PKD_API_KEY = "${ICAO_PKD_API_KEY}"
  SAPS_CRC_API_KEY = "${SAPS_CRC_API_KEY}"
  SITA_ESERVICES_API_KEY = "${SITA_ESERVICES_API_KEY}"
  DATABASE_URL = "${DATABASE_URL}"
  GITHUB_TOKEN = "${GITHUB_TOKEN}"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000
  publish = "dist/public"
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://replit.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.openai.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"