# Railway Deployment Configuration for DHA Digital Services Platform
# Department of Home Affairs - Government Digital Platform

[build]
builder = "NIXPACKS"
buildCommand = "npm ci && cd client && npm ci && cd .. && npm run build"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "npm start"

# Environment variables
[env]
PORT = "3000"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"