services:
  - type: web
    name: dha-digital-services
    env: node
    plan: starter
    buildCommand: npm install --force && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    branch: main

databases:
  # PostgreSQL database for persistent storage
  - name: ultra-queen-db
    databaseName: ultra_queen_ai
    user: ultra_queen_admin
    region: oregon # Same as web service
    plan: starter # or standard for production

# Static site for documentation (optional)
staticSites:
  - type: static
    name: ultra-queen-docs
    buildCommand: npm run build:docs
    staticPublishPath: ./docs/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff