services:
  - type: web
    name: dha-digital-services
    env: node
    region: frankfurt
    plan: pro
    buildCommand: ./enhanced-build.sh # Use enhanced build script
    startCommand: NODE_ENV=production node dist/server/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    healthCheckTimeout: 180
    healthCheckInterval: 15 # Reduced for faster response
    pullRequestPreviewsEnabled: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 70
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      # Universal API Override
      - key: UNIVERSAL_API_OVERRIDE
        value: true
      - key: BYPASS_API_VALIDATION
        value: true
      - key: FORCE_API_SUCCESS
        value: true
      # Self-Healing
      - key: AUTO_RECOVERY
        value: true
      - key: CIRCUIT_BREAKER_ENABLED
        value: true
      - key: GRACEFUL_DEGRADATION
        value: true
      # Monitoring Configuration
      - key: ENABLE_MONITORING
        value: true
      - key: MONITOR_INTERVAL
        value: 60000
      - key: MAX_RETRY_ATTEMPTS
        value: 3
      - key: ALERT_THRESHOLD
        value: 5
      # API Keys and Secrets (must be set in Render dashboard)
      - key: DATABASE_URL
        sync: true # Changed to true for proper sync
      - key: SESSION_SECRET
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: ENCRYPTION_KEY
        sync: true
      - key: OPENAI_API_KEY
        sync: true
      - key: ANTHROPIC_API_KEY
        sync: true
      # API Fallback Configuration
      - key: ENABLE_API_FALLBACK
        value: true
      - key: API_FALLBACK_TIMEOUT
        value: 5000
      - key: MAX_FALLBACK_ATTEMPTS
        value: 3
      # Extra failsafe environment variables
      - key: MAXIMUM_PROTECTION_MODE
        value: true
      - key: ENABLE_SELF_HEALING
        value: true
      - key: ENABLE_AUTO_RECOVERY
        value: true
      - key: ENABLE_ULTRA_MONITORING
        value: true

  - type: worker
    name: dha-monitoring-service
    runtime: node
    plan: starter
    buildCommand: ./build-fix.sh
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_MONITORING
        value: true
      - key: MONITOR_INTERVAL
        value: 60000
      - key: TARGET_SERVICE
        value: dha-digital-services
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: DATABASE_URL
      - key: ALERT_WEBHOOK_URL
        sync: false
      - key: DISABLE_PORT_BINDING
        value: true
    autoscaling:
      min: 1
      max: 1