version: "1"
services:
  - type: web
    name: dha-digital-services
    runtime: node
    plan: standard # Production-grade plan
    buildCommand: |
      npm ci --legacy-peer-deps
      npm run build
    startCommand: npm start
    autoscaling:
      min: 1
      max: 3
      targetMemoryPercent: 75
      targetCPUPercent: 75
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: VITE_ENCRYPTION_KEY
        sync: false
      - key: MASTER_ENCRYPTION_KEY
        sync: false
      - key: QUANTUM_ENCRYPTION_KEY
        sync: false
      - key: BIOMETRIC_ENCRYPTION_KEY
        sync: false
      - key: DOCUMENT_SIGNING_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: WORKATO_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: false

  - type: worker
    name: dha-monitoring-service
    runtime: node
    plan: starter
    buildCommand: npm ci --legacy-peer-deps
    startCommand: node server/monitor.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: DATABASE_URL
      - key: ALERT_WEBHOOK_URL
        sync: false
    autoscaling:
      min: 1
      max: 1