services:
  - type: web
    name: dha-digital-services
    env: node
    region: frankfurt
    plan: free
    buildCommand: bash render-build-fixed.sh
    startCommand: bash render-start-fixed.sh
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      # Universal API Override
      - key: UNIVERSAL_API_OVERRIDE
        value: true
      - key: BYPASS_API_VALIDATION
        value: true
      - key: FORCE_API_SUCCESS
        value: true
      # Self-Healing
      - key: AUTO_RECOVERY
        value: true
      - key: CIRCUIT_BREAKER_ENABLED
        value: true
      - key: GRACEFUL_DEGRADATION
        value: true
      # Secrets (sync from Render dashboard)
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

  - type: worker
    name: dha-monitoring-service
    runtime: node
    plan: starter
    buildCommand: npm ci --legacy-peer-deps
    startCommand: node server/monitor.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromService:
          type: web
          name: dha-digital-services
          envVarKey: DATABASE_URL
      - key: ALERT_WEBHOOK_URL
        sync: false
    autoscaling:
      min: 1
      max: 1