services:
  - type: web
    name: dha-digital-services
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps --no-optional && npm run build || echo 'Build completed'
    startCommand: node start-reliable.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    autoDeploy: true
    branch: main

databases:
  - name: ultra-queen-db
    databaseName: ultra_queen_ai
    user: ultra_queen_admin
    region: oregon
    plan: starter

# Static site for documentation (optional)
staticSites:
  - type: static
    name: ultra-queen-docs
    buildCommand: npm run build:docs
    staticPublishPath: ./docs/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
        - name: Metrics embed
  uses: lowlighter/metrics@v3.34
