name: Autofix

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for lock file
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json missing!"
            exit 1
          fi
      - name: Lint
        run: npm run lint || true
      - name: Auto-fix
        run: npm run lint -- --fix || true
        
- name: Vercel Action
  uses: amondnet/vercel-action@v41.1.4

- name: Vercel Actions
  uses: nexterias/actions-vercel@v1.2.3

- name: Vercel Production Deployment
  uses: yuito-it/GitHub-Vercel-Actions@v1.0.2

- name: Vercel Preview URL with Status Polling
  uses: RoyBkker/github-action-vercel-preview-url-poller@v1.0.6

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
